name: Integration
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: |
          go mod download
      - name: Run unit-tests
        run: |
          go test -race -covermode=atomic -coverprofile=cov.out -coverpkg=./... -short ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: cov.out
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Install dependencies
        run: |
          go mod download && go mod vendor
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          only-new-issues: true
          args: --timeout=3m -v
